CREATE TABLE companies (
  company_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_code VARCHAR2(30),
  company_name VARCHAR2(150) NOT NULL,
  address VARCHAR2(255),
  city VARCHAR2(100),
  country VARCHAR2(100),
  is_active CHAR(1) DEFAULT 'Y' NOT NULL,
  is_deleted CHAR(1) DEFAULT 'N' NOT NULL,
  deleted_at TIMESTAMP(6),
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE warehouses ADD (
  company_id NUMBER
);

CREATE INDEX warehouses_company_ix ON warehouses (company_id);

ALTER TABLE warehouses ADD CONSTRAINT warehouses_company_fk
  FOREIGN KEY (company_id) REFERENCES companies (company_id);

CREATE TABLE warehouse_transfers (
  transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_number VARCHAR2(50) NOT NULL,
  company_id NUMBER NOT NULL,
  from_warehouse_id NUMBER NOT NULL,
  to_warehouse_id NUMBER NOT NULL,
  status VARCHAR2(20) NOT NULL,
  notes VARCHAR2(255),
  requested_by NUMBER NOT NULL,
  approved_by NUMBER,
  approved_at TIMESTAMP(6),
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT warehouse_transfers_company_fk FOREIGN KEY (company_id)
    REFERENCES companies (company_id),
  CONSTRAINT warehouse_transfers_from_fk FOREIGN KEY (from_warehouse_id)
    REFERENCES warehouses (warehouse_id),
  CONSTRAINT warehouse_transfers_to_fk FOREIGN KEY (to_warehouse_id)
    REFERENCES warehouses (warehouse_id),
  CONSTRAINT warehouse_transfers_requested_fk FOREIGN KEY (requested_by)
    REFERENCES app_users (user_id),
  CONSTRAINT warehouse_transfers_approved_fk FOREIGN KEY (approved_by)
    REFERENCES app_users (user_id)
);

CREATE TABLE warehouse_transfer_items (
  transfer_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id NUMBER NOT NULL,
  product_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT transfer_items_transfer_fk FOREIGN KEY (transfer_id)
    REFERENCES warehouse_transfers (transfer_id),
  CONSTRAINT transfer_items_product_fk FOREIGN KEY (product_id)
    REFERENCES products (product_id)
);

CREATE INDEX transfer_items_transfer_ix ON warehouse_transfer_items (transfer_id);

CREATE TABLE returns (
  return_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_number VARCHAR2(50) NOT NULL,
  sale_id NUMBER,
  warehouse_id NUMBER NOT NULL,
  cashier_id NUMBER NOT NULL,
  reason VARCHAR2(255),
  status VARCHAR2(20) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT returns_sale_fk FOREIGN KEY (sale_id)
    REFERENCES sales_transactions (sale_id),
  CONSTRAINT returns_warehouse_fk FOREIGN KEY (warehouse_id)
    REFERENCES warehouses (warehouse_id),
  CONSTRAINT returns_cashier_fk FOREIGN KEY (cashier_id)
    REFERENCES app_users (user_id)
);

CREATE TABLE return_items (
  return_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id NUMBER NOT NULL,
  product_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  unit_price NUMBER,
  tax_amount NUMBER,
  line_total NUMBER,
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT return_items_return_fk FOREIGN KEY (return_id)
    REFERENCES returns (return_id),
  CONSTRAINT return_items_product_fk FOREIGN KEY (product_id)
    REFERENCES products (product_id)
);

CREATE TABLE inventory_receipts (
  receipt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number VARCHAR2(50) NOT NULL,
  warehouse_id NUMBER NOT NULL,
  product_id NUMBER NOT NULL,
  supplier_id NUMBER,
  quantity NUMBER NOT NULL,
  received_at TIMESTAMP(6),
  created_by NUMBER,
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT receipts_warehouse_fk FOREIGN KEY (warehouse_id)
    REFERENCES warehouses (warehouse_id),
  CONSTRAINT receipts_product_fk FOREIGN KEY (product_id)
    REFERENCES products (product_id),
  CONSTRAINT receipts_supplier_fk FOREIGN KEY (supplier_id)
    REFERENCES suppliers (supplier_id),
  CONSTRAINT receipts_created_by_fk FOREIGN KEY (created_by)
    REFERENCES app_users (user_id)
);
