-- Oracle Autonomous Database Schema

-- 1. BRANCHES Table
CREATE TABLE BRANCHES (
    branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255)
);

-- 2. PRODUCTS Table
CREATE TABLE PRODUCTS (
    product_sku VARCHAR2(50) PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    base_price NUMBER(10, 2) NOT NULL,
    category VARCHAR2(50),
    supplier_id NUMBER
);

-- 3. INVENTORY Table
CREATE TABLE INVENTORY (
    product_sku VARCHAR2(50),
    branch_id NUMBER,
    quantity NUMBER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inventory PRIMARY KEY (product_sku, branch_id),
    CONSTRAINT fk_inv_product FOREIGN KEY (product_sku) REFERENCES PRODUCTS(product_sku),
    CONSTRAINT fk_inv_branch FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- 4. SALES Table
CREATE TABLE SALES (
    transaction_id VARCHAR2(50) PRIMARY KEY,
    branch_id NUMBER,
    cashier_id NUMBER,
    final_amount NUMBER(10, 2),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_branch FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- 5. SALE_ITEMS Table
CREATE TABLE SALE_ITEMS (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR2(50),
    product_sku VARCHAR2(50),
    quantity NUMBER,
    unit_price NUMBER(10, 2),
    CONSTRAINT fk_items_txn FOREIGN KEY (transaction_id) REFERENCES SALES(transaction_id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_sku) REFERENCES PRODUCTS(product_sku)
);
